
#ifndef __APP_VERSION_H__
#define __APP_VERSION_H__



#define MYAPP_NAME				"ThProcLib"
 
#define MYAPP_VERSION_MAJOR		1
#define MYAPP_VERSION_MINOR		0
#define MYAPP_VERSION_SUB		6
#define MYAPP_VERSION_MICRO		0	
 


#ifdef _DEBUG
#define MYAPP_VERSION_NAME		Debug
#else
#define MYAPP_VERSION_NAME		
#endif

#ifdef  DEMO_VERSION
#define DEMO_STR (Demo)
#else
#define DEMO_STR 
#endif

#define MYAPP_VERSION_FULL			MYAPP_VERSION_DOT MYAPP_VERSION_NAME DEMO_STR
#define MYAPP_VERSION_STRING		MYAPP_QSTRING(MYAPP_VERSION_FULL)

#define MYAPP_VERSION_DOT			MYAPP_VERSION_MAJOR.MYAPP_VERSION_MINOR.MYAPP_VERSION_SUB.MYAPP_VERSION_MICRO
#define MYAPP_VERSION_COMMA			MYAPP_VERSION_MAJOR,MYAPP_VERSION_MINOR,MYAPP_VERSION_SUB,MYAPP_VERSION_MICRO

#define MYAPP_QSTRING(s)			MYAPP_QQSTRING(s)
#define MYAPP_QQSTRING(s)			#s

#endif //__APP_VERSION_H__
